version: '3.1'

services:
  springboot-carrentalapp:
    container_name: carrentalapp
    image: carrentalapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/carrentalapp
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1234
  mysqldb:
    container_name: mysqldb
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: carrentalapp
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: "mysql -usa -p1234 content -e 'select 1'"
      interval: 1s
      retries: 120